R/pct_change.R
R/slide.R
vignettes/pct_change.Rmd
vignettes/slide.Rmd

Fixed some small things in the percentage change vignette:
- changed the sliding window to be centered (more natural here)
- mentioned the connection to growth rates
- just went with 7-day averaged case data from the start

Improve percentage change vignette

---

DESCRIPTION
R/growth_rate.R
R/outliers.R

- Edit slightly to make code and error/warning messages between `growth_rate()` and `detect_outlr()` to be a bit more unified
- Remove line in DESCRIPTION that suggests `delphi.epidata`. This is not ready for prime time yet, and in addition, I think it has still been causing some errors for people to install the package

Edits to duplicate values checks

---

R/data.R
man/archive_cases_dv_subset.Rd
vignettes/advanced.Rmd
vignettes/archive.Rmd

fix attribution splicing in files that use doctor visits

---

DESCRIPTION
man/archive_cases_dv_subset.Rd
man/incidence_num_outlier_example.Rd
man/jhu_csse_county_level_subset.Rd
man/jhu_csse_daily_subset.Rd

In description, mentioned `epi_archive` functionality (as "provides another data structure to
work with revisions to these data sets over time") and changed  "epidemiological data sets measured over space and time" -> "epidemiological data reported by location and time" as originally written in the [issue](https://github.com/cmu-delphi/epiprocess/issues/80).

Mentioned `epi_archive` functionality and changed "over space and time" in package description

---

R/slide.R
man/epi_slide.Rd

As per our discussion @brookslogan, updated the `epi_slide` examples to remove a nonessential var in the output so that the new col is ensured to be printed when the usual setting of `getOption("width")` of 80 is used in R or RStudio. Should be good to go now.

Updated `epi_slide` examples to ensure new col is printed

---

R/archive.R
R/methods-epi_archive.R

As per [issue 90](https://github.com/cmu-delphi/epiprocess/issues/90), removed time filter relative to the version value in `as_of` function.

Removed time filter in relation to version in `as_of`

---

R/archive.R
man/as_epi_df.Rd

Toggle on the `na.rm` option (via the custom `Min` and `Max` functions) so even if an `epi_archive`'s `time_value` field contains some missing values (`NA`) printed min/max values are still useful. Prints `NA` if _all_ `time_value`s are missing and "no non-missing arguments" warning is raised, or if an un-caught warning occurs.
- `R/archive.R` - added `na.rm` setting and try-catch to handle all-missing case.
- `man/as_epi_df.Rd` - not my changes, showed up when I re-`document()`ed
Closes https://github.com/cmu-delphi/epiprocess/issues/106

Ignore `NA`s when printing an archive's min/max `time_value`

---

R/methods-epi_df.R
man/as_epi_archive.Rd
man/as_epi_df.Rd
man/epi_archive.Rd
man/epi_slide.Rd
man/epix_as_of.Rd
man/epix_slide.Rd

Updated `[.epi_df` code to simplify the code and to fix [Issue 104 in epipredict](https://github.com/cmu-delphi/epipredict/issues/104) as discussed with Maggie and Daniel.

Addressed the sources of the conflicts between epipredict and epiprocess (see Issue 104 in epipredict)

---

R/epi_df.R
man/as_epi_archive.Rd
man/as_epi_df.Rd
man/epi_archive.Rd
man/epi_slide.Rd
man/epix_as_of.Rd
man/epix_slide.Rd
man/new_epi_df.Rd
tests/testthat/test-epi_df.R
tests/testthat/test-methods-epi_df.R
vignettes/epiprocess.Rmd

Addresses #182 
Changes:
- Update `new_epi_df` examples so that (i) `additional_metadata` argument is type `list` instead of `vector` and (ii) there is an example with multiple `other_keys`
- Add a check in `new_epi_df` to ensure `additional_metadata` is a `list`
- Write a test for the previous change
I checked in `epipredict` for calls to `as_epi_df` and all `additional_metadata` arguments there are `lists` so this change will not break `epipredict`. Afaik there aren't any dependencies on `epiprocess` other than `epipredict`.

[Issue 182] Update `epi_df` examples, check `additional_metadata` type at construction

---

DESCRIPTION
data-raw/archive_cases_dv_subset.R
data-raw/incidence_num_outlier_example.R
data-raw/jhu_csse_county_level_subset.R
data-raw/jhu_csse_daily_subset.R
vignettes/advanced.Rmd
vignettes/aggregation.Rmd
vignettes/archive.Rmd
vignettes/correlation.Rmd
vignettes/epiprocess.Rmd
vignettes/growth_rate.Rmd
vignettes/outliers.Rmd
vignettes/slide.Rmd

This should address the issues noted [here](https://github.com/cmu-delphi/epidatr/issues/31), allowing us to point to the main repo (in `cmu-delphi/` org) for the new delphi-epidata R client package without upsetting `devtools`, `pak`, `renv`, or CI.  To be merged after https://github.com/cmu-delphi/epidatr/pull/39.

Use renamed `delphi.epidata` pkg `epidatr` (& its new repo name)

---

DESCRIPTION
R/methods-epi_df.R
tests/testthat/test-methods-epi_df.R

Since Issues https://github.com/cmu-delphi/epiprocess/issues/192, https://github.com/cmu-delphi/epiprocess/issues/193, and https://github.com/cmu-delphi/epiprocess/issues/194 are closely related, addressed all three here.
After discussion with Logan, made the following changes to `[.epi_df` code for the written issue:
- Issue https://github.com/cmu-delphi/epiprocess/issues/192: Any key columns that have been selected out from an `epi_df` are removed from other_keys in the metadata (refer to the ex in that issue).
- Issue https://github.com/cmu-delphi/epiprocess/issues/193: Dropped all metadata when decay to tibble.
- Issue https://github.com/cmu-delphi/epiprocess/issues/194: Abort if column duplication in an `epi_df` (to be consistent with tibble behaviour).

Addressed issues 192-194

---

DESCRIPTION
man/as_epi_archive.Rd
man/as_epi_df.Rd
man/epi_archive.Rd
man/epi_slide.Rd
man/epix_as_of.Rd
man/epix_slide.Rd

To resolve Issue #210, switched to the remote repo: https://github.com/glmgen/genlasso because genlasso was removed from CRAN.

Use glmgen/genlasso because package was removed from CRAN

---

R/archive.R
man/as_epi_archive.Rd
man/as_epi_df.Rd
man/epi_archive.Rd
man/epi_slide.Rd
man/epix_as_of.Rd
man/epix_slide.Rd

To resolve Issue #208 removed the two `as_tibble()` calls in archive slide function so that `epix_slide()` is compatible with `arx_forecaster()` from epipredict (to be able to slide an ARX forecaster over an archive). Making a separate issue to deal with the metadata.

Removed as_tibble() calls in archive slide fun

---

R/methods-epi_archive.R
tests/testthat/test-epix_merge.R

Also:
- Add an internal warning + recovery if our DT preprocessing unexpectedly
produces a DT with a different key (although in a way that won't catch if we
accidentally mutated the original DT's key and matched it in the intermediate
DT). If this is triggered, we will likely need to rethink/bugfix some other DT
usage in other code which may have made similar assumptions about certain DT
operations not dropping/modifying the key.
- Edit the input to one set of epix_merge tests to make the truncate test more
restrictive than it would have been otherwise, and edit a non-truncate test with
an `expected` value that changes as a result.
Closes #200.

Fix `epix_merge` `sync="truncate"` err (`with=F` no `j`), add tests

---

DESCRIPTION
NEWS.md
pkgdown/extra.scss

Part of #177.
Decisions to be made:
- Is this version breakdown appropriate?
- Is this changelog format appropriate?  What changes do we want to make now?  And moving forward?
- Should `main` continue to be a development branch?  If so, we can just merge this into main.  If not, we should PR the latest release into main so it gets the right version number[, or] just bump the version number in this PR [and release/tag it] (--> 0.5.1).
Dan & Dmitry, your input would be very helpful here.
I've prepared some branches like 0.1.0_prep that we could then tag as 0.1.0 if we're happy with the retro version numbering.  We should probably update the changelog inside of PRs moving forward.
(Note: we are trying to follow semver, but the .9999 thing wouldn't follow.  It's to mark it as a dev version, …

Add changelog (NEWS.md), associated pkgdown styling

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
README.md

```{r}
usethis::use_github_action("pkgdown")
usethis::use_github_action_check_release() # and follow instructions regarding badge
```

Update GitHub Actions themselves, not just embedded dependencies

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
DESCRIPTION
NEWS.md
R/methods-epi_archive.R
R/slide.R
README.md
_pkgdown.yml
man/epi_slide.Rd
man/epix_fill_through_version.Rd
man/epix_slide.Rd
vignettes/aggregation.Rmd
vignettes/archive.Rmd
vignettes/compactify.Rmd
vignettes/correlation.Rmd
vignettes/epiprocess.Rmd
vignettes/growth_rate.Rmd
vignettes/outliers.Rmd
vignettes/slide.Rmd

Keeping this in the `dev` branch as pushing to `main` will break `epipredict`, and it might make sense to incorporate repairs for the current breaking changes with those for some other planned breaking changes that are hopefully imminent.

Bump version to 0.6.0

---

R/methods-epi_archive.R
man/as_epi_df.Rd
man/epix_slide.Rd

Add example to `epix_slide` documentation comparing the same computation for `all_versions = TRUE` and `all_versions = FALSE`.

add epix_slide example comparing same computation with all_vers FALSE

---

R/grouped_epi_archive.R
R/slide.R
R/utils.R
tests/testthat/test-utils.R

Addresses https://github.com/cmu-delphi/epiprocess/pull/313/files#r1199169940
Now that `epi[x]_slide` both support use of `ref_time_value` in computations, computations passed as functions expect 3 arguments. Remove the `n_mandatory_f_args` placeholder arg from `assert_sufficient_f_args`.

Drop the `n_mandatory_f_args` placeholder arg from `assert_sufficient_f_args`

---

DESCRIPTION
R/utils.R
inst/COPYRIGHTS
man/epi_slide.Rd
man/epix_slide.Rd
man/reexports.Rd

Add `rlang` authors and copyright holder to DESCRIPTION file. Add COPYRIGHT file. Add `rlang` license text to the documentation for `as_slide_computation`, noting aspects of the original code that were kept and changed.
Partially addresses https://github.com/cmu-delphi/epiprocess/issues/327

Attribute code borrowed/modified from `rlang` for use in `as_slide_computation`

---

.github/workflows/pkgdown.yaml

This makes it so that pkgdown will only run if the repo is owned by cmu-delphi directly. I'd rather pkgdown stopped trying to run on my fork whenever I sync it with main or dev, causing failing build notifications. This should solve it, taken from [here](https://github.com/orgs/community/discussions/26409), and working on epidatr.

ci: stop building pkgdown on forks

---

DESCRIPTION
NEWS.md
data-raw/archive_cases_dv_subset.R
data-raw/incidence_num_outlier_example.R
data-raw/jhu_csse_county_level_subset.R
data-raw/jhu_csse_daily_subset.R
vignettes/advanced.Rmd
vignettes/aggregation.Rmd
vignettes/archive.Rmd
vignettes/correlation.Rmd
vignettes/epiprocess.Rmd
vignettes/growth_rate.Rmd
vignettes/outliers.Rmd
vignettes/slide.Rmd

- Fixes vignettes currently failing.
- Fixes dataset downloading code that relies on epidatr. It might seem like there a lot of changes, but most of those are my IDE automatically applying styler when I saved.
- Fixes formatting errors in NEWS.md.

fix: update for epidatr 1.0.0

---

NEWS.md

Since `main` is already on 0.7.0 and it's stable-enough, we should make it a release. This updates the NEWS with a few bullets from the release notes generated by the current `main` branch. 
After we merge this, we can make a release 0.7.0, then bump the dev branch to 0.7.0.9000 (see Nat's comment in #383) and starting adding PR change lines under that heading.

docs: update news for 0.7.0 release

---

DESCRIPTION
NEWS.md
R/archive.R
man/as_epi_archive.Rd
man/epi_archive.Rd

whenever I run check locally, I get a lot of errors about various documentation bits missing. This fills those in.
Closes #132 apparently.

fixing constant check warnings

---

R/slide.R
R/utils.R
tests/testthat/test-utils.R

This is just a few minor refactors, removing some redundant checks, clarifying naming, adding some comments.

Simplify and clarify parts of `epi_slide` implementation

---

.github/CODEOWNERS
.github/pull_request_template.md

Disable auto review requests to CODEOWNERS by removing the file altogether.

Disable auto review assignment, add PR template

---

.github/workflows/auto_semver_bump.yaml

not sure if this is quite the right way. I also added a repo secret `SEMVER_BUMPER_KEY`, which has both a [secret](https://github.com/cmu-delphi/epiprocess/settings/secrets/actions) and a [deploy key](https://github.com/cmu-delphi/epiprocess/settings/keys) with write access

patch version bumper for branch permissions

---

.lintr

Please:
-   [x] Make sure this PR is against "dev", not "main".
-   [x] Request a review from one of the current epiprocess main reviewers:
-   [x] Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
Always increment the patch version number (the third number), unless you are
making a release PR from dev to main, in which case increment the minor
version number (the second number).
-   [x] Describe changes made in NEWS.md, making sure breaking changes
0.7.2, then write your changes under the 0.8 heading).
- Mostly line length 120, cyclocomp off
- Repo changes, no need for changelog/version

lint: copy .lintr from epidatr

---

R/epi_df.R
R/methods-epi_df.R
R/outliers.R
R/slide.R
man-roxygen/basic-slide-params.R
man-roxygen/detect-outlr-return.R
man-roxygen/epi_df-params.R
man-roxygen/opt-slide-details.R
man-roxygen/opt-slide-params.R
man-roxygen/outlier-detection-options.R
man-roxygen/x-y.R
man-roxygen/x.R
man/as_tibble.epi_df.Rd
man/as_tsibble.epi_df.Rd
man/detect_outlr.Rd
man/detect_outlr_rm.Rd
man/detect_outlr_stl.Rd
man/epi_slide.Rd
man/epi_slide_mean.Rd
man/epi_slide_opt.Rd
man/epi_slide_sum.Rd
man/print.epi_df.Rd

Please:
PR).
process.
Move duplicated params and other doc text to template files in `man-roxygen` so it can be easily changed all at once.
Note: `R/methods-epi_archive.R` is not updated here due to potential conflicts with pending #431.

Move some documentation to templates for easier updating

---

DESCRIPTION
NEWS.md
R/utils.R
tests/testthat/test-utils.R

- Previously we guessed YYYYww numeric as "year", almost surely wrong. But we can't easily/reliably tell what type of yearweek it is, so just use "custom" to avoid various/bad guesses in time_type-reliant code.
- Don't use <int> <= <chr>; seemed nonimpactful in this case, at least in tested locale.
Please:
PR).
process.
- …

Guess YYYYww numeric as "custom", fix incidental typo

---

DESCRIPTION
NEWS.md
vignettes/epiprocess.Rmd

Avoid `filter(cases==1)`: this should either
* involve `filter(status == "confirmed")` instead, or
* involve no filter, and let `sum` take care of things.
We should generally expect the latter approach to be RAM-friendlier (one new column vs. new filtered vectors for every column), so implement the latter approach.
Reformat the code a bit to try to make it read better.
Clarify the description of the example; make clear we're deriving from line list data.
`complete` the data to make the set of `time_value`s evenly spaced and the same for every `geo_value`; even though it doesn't impact the plots, we're demonstrating how to get things into `epi_df` format, and many functions we'd use on `epi_df`s will expect things in this format.

Avoid `filter(cases==1)`, better describe & `complete` Ebola example

---

DESCRIPTION
NEWS.md
vignettes/epiprocess.Rmd

Please:
PR).
process.
This addresses some feedback we received from Guidehouse on the landing page; here are my notes:
- We should provide more context on landing page: why, what need, what ?? addresses; highlighting more e.g. the top 2 novel features.
- Useful in landing page to have a little more detail e.g. about 7dav-ing?
- …

Address Guidehouse feedback on landing page

---

R/grouped_epi_archive.R
R/slide.R

Please:
PR).
process.
`... <- missing_arg()` consistently causes warning in tests `Warning: : ... may be used in an incorrect context`. Switch to another way of assigning to the variable `...` to avoid this.
Closes https://github.com/cmu-delphi/epiprocess/issues/465

Assign to dots using `assign` to avoid CI warning

---

NEWS.md
vignettes/slide.Rmd

Please:
PR).
process.
Minor update on `slide.Rmd`, removes reference to `left` and `right` and change to `before` and `after`.  

`slide.Rmd` seems to contain legacy info on `epi_slide`

---

tests/testthat/test-epi_slide.R

Please:
PR).
process.
- use expect_equal for slide tests
- Resolves #473

fix(epi_slide): use expect_equal for slide tests

---

tests/testthat/test-as_tibble-decay.R
tests/testthat/test-methods-epi_df.R

Please:
PR).
process.
Not bumping the version or adding to NEWS because it only changes tests, and is strictly upstream changes.
I added a skip that only tests for grouping's presence if the version of `tsibble` is before 1.1.5 specifically.

test grouping only before tsibble 1.1.5

---

DESCRIPTION
NEWS.md

Please:
PR).
process.
Bumping version before release.

doc: bump to 0.8

---

DESCRIPTION
NEWS.md
R/methods-epi_df.R
R/slide.R
R/utils.R
man/complete.epi_df.Rd
tests/testthat/test-epi_slide.R
tests/testthat/test-epix_slide.R

Please:
PR).
process.
- Resolves #503

fix: `before=Inf` in opt functions now actually works

---

DESCRIPTION
R/autoplot.R
R/correlation.R
R/growth_rate.R
R/outliers.R
R/slide.R
man-roxygen/basic-slide-details.R
man-roxygen/basic-slide-params.R
man-roxygen/opt-slide-details.R
man-roxygen/opt-slide-params.R
man/epi_slide.Rd
man/epi_slide_mean.Rd
man/epi_slide_opt.Rd
man/epi_slide_sum.Rd
tests/testthat/test-epi_slide.R
vignettes/advanced.Rmd
vignettes/aggregation.Rmd
vignettes/archive.Rmd
vignettes/slide.Rmd

Please:
PR).
process.
Prototype of new slide interface. Fixing tests takes a long time, want to make sure we agree on inner logic and deprecation handling before I tackle all that. The core logic may be easier to read outside the diffs, so reproducing here:
```r
if (!is.null(before) || !is.null(after)) {
cli_abort("`before` and …
```

wip: rework slide window args

---

DESCRIPTION
R/archive.R

Please:
PR).
- [-] Request a review from one of the current main reviewers:
- [-] Describe changes made in NEWS.md, making sure breaking changes
process.
This fixes a typo that appears to have no impact, but might confuse us in the future.  The impacted `x_arg` never actually seems to be used, so maybe something else should be …

Fix validate_version_bound typo

---

DESCRIPTION
NEWS.md
data-raw/jhu_csse_county_level_subset.R
vignettes/aggregation.Rmd

Please:
PR).
process.
* just download the files, don't import covidcast
* covidcast depends on sf which is tough to install (it just refuses to compile on my machine) and my renv keeps trying to install ALL dependencies

refactor: remove Suggests dependence on covidcast

---

README.Rmd
README.md
vignettes/epi_archive.Rmd
vignettes/epiprocess.Rmd

Sync dev -> main

---

R/methods-epi_df.R
man/complete.epi_df.Rd

Please:
PR).
- [-] Request a review from one of the current main reviewers:
- [-] Makes sure to bump the version number in `DESCRIPTION`. Always increment
- [-] Describe changes made in NEWS.md, making sure breaking changes
process.
- @XuedaShen  noticed an issues with the code formatting.
This fixes that + tweaks the summary. …

docs(complete.epi_df): fix backticks, tweak 1-line summary

---

.github/workflows/pkgdown.yaml
DESCRIPTION
_pkgdown.yml

delphidocs on dev

---

R/slide.R
man/epiprocess-package.Rd

Please:
PR).
- [-] Request a review from one of the current main reviewers:
- [-] Makes sure to bump the version number in `DESCRIPTION`. Always increment
- Skipping bumping as this is so near 0.10.0 release PRs.
- [-] Describe changes made in NEWS.md, making sure breaking changes
- should already be covered by the the `epi_slide_opt` change description
- See [DEVELOPMENT.md](DEVELOPMENT.md) for more …

Improve `epi_slide_{sum,mean}` unsupported-arg messages.

---

vignettes/epi_df.Rmd

This is part 1 of a 3-part PR.  (Checks and lints connect it to the other parts.)  A recombined PR will be made to dev.  Some of these process things will be handled there.  I don't want to do more git surgery.  Probably should have just had a couple reviewers for the original PR and pointed to different files.
Please:
- [-] Make sure this PR is against "dev", not "main" (unless this is a release
PR).
- [-] Request a review from one of the current main reviewers:
- [-] Makes sure to bump the version number in `DESCRIPTION`. Always increment
- [-] Describe changes made in NEWS.md, making sure breaking …

Fix age group rate aggregation example

---

.github/workflows/doc-preview.yaml

Please:
PR).
process.
This adds the docs preview command: /preview-docs to this package. 

ci: add netlify preview

---

DESCRIPTION
vignettes/correlation.Rmd

Please:
PR).
process.
Accompanies https://github.com/cmu-delphi/epidatasets/pull/16

Change as-of date in vignette example to match new `epidatasets::covid_case_death_rates_extended` as-of date

---

DESCRIPTION
R/key_colnames.R
R/methods-epi_archive.R
R/utils.R
man/format_chr_with_quotes.Rd
tests/testthat.R
tests/testthat/test-compactify.R
tests/testthat/test-epix_merge.R

Please:
PR).
- [-] Describe changes made in NEWS.md, making sure breaking changes
- don't think this is worth a NEWS entry.
process.
- See #631 for context.  epipredict updated to use `hardhat::quantile_pred()` rather than its own `dist_quantiles()` backed by `{distributional}`.  It has some extra constraints and a bug, and …

Address `dist_quantiles()` deprecation

---

R/archive.R
R/epi_slide_opt_archive.R
R/epi_slide_opt_edf.R
R/patch.R
man/across_ish_names_info.Rd
man/epi_slide_opt_archive_one_epikey.Rd
man/update_is_locf.Rd
tests/testthat/test-epi_slide_opt_archive.R

Please:
- [NA] Makes sure to bump the version number in `DESCRIPTION`. Always increment
- `/document` to check the package documentation and fix any issues.
- `/style` to check the style and fix any issues.
- `/preview-docs` to preview the docs.
- See Actions GitHub tab to track progress of these commands.
process.
- Resolves …

comments and some nit rewrites

---

DESCRIPTION
_pkgdown.yml

Please:
PR).
- `/document` to check the package documentation and fix any issues.
- `/style` to check the style and fix any issues.
- `/preview-docs` to preview the docs.
- See Actions GitHub tab to track progress of these commands.
process.

needs github.com for linking to source in pkgdown

---

.github/pull_request_template.md

so that following in order will `\style` roxygen `@examples` and then `/document` will propagate styled examples to the .Rd files, rather than leaving .Rd files out of date.
Please:
PR).
- `/document` to check the package documentation and fix any issues.
- `/style` to check the style and fix any issues.
- `/preview-docs` to preview the docs.
- See Actions GitHub tab to track progress of these commands.
- …

List `/style` before `/document` in PR template
